In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Imports successful")

Imports successful

In [14]:
df = pd.read_csv("../data/raw/Titanic dataset.csv")
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [15]:
print("Shape:", df.shape)

Shape: (1309, 14)

In [16]:
print("Column names:")
print(df.columns.tolist())

Column names:
['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest']

In [17]:
print("Data types:")
print(df.dtypes)

Data types:
pclass         int64
survived       int64
name             str
sex              str
age          float64
sibsp          int64
parch          int64
ticket           str
fare         float64
cabin            str
embarked         str
boat             str
body         float64
home.dest        str
dtype: object

In [18]:
print("Missing values:")
print(df.isnull().sum())

Missing values:
pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [19]:
print("Unique values:")
print(df.nunique())

Unique values:
pclass          3
survived        2
name         1307
sex             2
age            98
sibsp           7
parch           8
ticket        929
fare          281
cabin         186
embarked        3
boat           27
body          121
home.dest     369
dtype: int64

## Dataset Information

Dataset: Titanic Dataset

Source: Kaggle – Titanic: Machine Learning from Disaster  
Source URL: https://www.kaggle.com/datasets/sakshisatre/titanic-dataset

License: The dataset is provided by Kaggle for use in the Titanic competition and is publicly available for educational and analytical purposes.

Why I chose this dataset:
I chose the Titanic dataset because it contains both numerical and categorical variables and has enough rows to practice data cleaning, grouping, feature engineering, NumPy computations, and visualization. It is also a well-known dataset, which makes it easier to understand the meaning of the variables and focus on learning the data analysis process.

## Task 2

In [22]:
df.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [23]:
df.dtypes

pclass         int64
survived       int64
name             str
sex              str
age          float64
sibsp          int64
parch          int64
ticket           str
fare         float64
cabin            str
embarked         str
boat             str
body         float64
home.dest        str
dtype: object

In [24]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df[df.isnull().any(axis=1)].head() #lets us see actual rows containing missing values.

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [27]:
# Fill missing Age values with the median because Age is numeric
# and the median is less affected by unusually high or low ages.
df["age"] = df["age"].fillna(df["age"].median())

# Fill the missing Fare value with the median because Fare is numeric
# and only one value is missing.
df["fare"] = df["fare"].fillna(df["fare"].median())

# Fill missing Embarked values with the most common category (mode)
# because only two values are missing.
df["embarked"] = df["embarked"].fillna(df["embarked"].mode()[0])

# Create a Cabin missing-value indicator because Cabin has many
# missing values, and the fact that a cabin is unknown may itself be useful.
df["cabin_missing"] = df["cabin"].isna().astype(int)

# No duplicate rows were found, so no rows were removed.

print("Cleaning completed.")

Cleaning completed.

In [28]:
df.isnull().sum()

pclass              0
survived            0
name                0
sex                 0
age                 0
sibsp               0
parch               0
ticket              0
fare                0
cabin            1014
embarked            0
boat              823
body             1188
home.dest         564
cabin_missing       0
dtype: int64

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df.dtypes

pclass             int64
survived           int64
name                 str
sex                  str
age              float64
sibsp              int64
parch              int64
ticket               str
fare             float64
cabin                str
embarked             str
boat                 str
body             float64
home.dest            str
cabin_missing      int64
dtype: object